name: Request a New Property
description: Request to add a new property to the OBO Metadata Ontology (OMO).
title: Request for adding property [NAME] to OMO
labels: [ new property ]
assignees:
  - matentzn
body:
  - type: markdown
    attributes:
      value: |
        Use this form to add a new property to the OBO Metadata Ontology.
  - type: input
    id: iri
    attributes:
      label: IRI
      description: If the property already exists provide the full IRI here.
      placeholder: ex. http://www.w3.org/2000/01/rdf-schema#label
  - type: input
    id: label
    attributes:
      label: Label
      description: What should be the canonical label of your property?
      placeholder: ex. term editor
  - type: textarea
    id: definition
    attributes:
      label: Definition of the property
      description: Please provide a short definition of the property.
    validations:
      required: true
  - type: input
    id: parent
    attributes:
      label: Parent property
      description: If there is a suitable parent property in OMO, please provide it here.
  - type: dropdown
    id: range
    attributes:
      label: What is the range of the property in question?
      options:
        - xsd:string
        - xsd:double
        - xsd:integer
        - Class (IRI)
        - Individual (IRI)
        - Data Property (IRI)
        - Object Property (IRI)
        - Annotation Property (IRI)
        - Any URI (IRIs, URLs, etc)
        - other (indicate in example of use below)
    validations:
      required: true
  - type: textarea
    id: examples
    attributes:
      label: Examples of use
      description: |
        Provide an example of use.
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation to add
      description: |
        Explain why this particular property should be added. If the property already exists,
        explain why it should be re-used, and where it is imported from.
    validations:
      required: true
  - type: input
    id: contributor-orcid
    attributes:
      label: ORCID, ROR or Wikidata identifier of the contributor
      description: Provide an ORCID (https://orcid.org), Wikidata (https://www.wikidata.org/) or ROR (https://ror.org/) identifier for attribution and provenance purposes.
      placeholder: e.g. https://orcid.org/0000-0003-4423-4370
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: OMO Checklist
      description: |
        To be considered for inclusion in OMO, a new property must meet certain requirements. To ensure you are aware of some of its key points, please review the checklist below.
      options:
        - label: I believe the property is generally useful beyond my specific ontology needs.
          required: true
        - label: There is no other property in OMO that covers the same use case.
          required: true

